/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthLogoutRouteImport } from './routes/oauth/logout'
import { Route as OauthLoginApiRouteImport } from './routes/oauth/login-api'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as JwksJsonRouteImport } from './routes/jwks.json'
import { Route as OauthClientMetadataJsonRouteImport } from './routes/oauth/client-metadata.json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLogoutRoute = OauthLogoutRouteImport.update({
  id: '/oauth/logout',
  path: '/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginApiRoute = OauthLoginApiRouteImport.update({
  id: '/oauth/login-api',
  path: '/oauth/login-api',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const JwksJsonRoute = JwksJsonRouteImport.update({
  id: '/jwks/json',
  path: '/jwks/json',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataJsonRoute = OauthClientMetadataJsonRouteImport.update({
  id: '/oauth/client-metadata/json',
  path: '/oauth/client-metadata/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jwks/json': typeof JwksJsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/oauth/client-metadata/json': typeof OauthClientMetadataJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jwks/json': typeof JwksJsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/oauth/client-metadata/json': typeof OauthClientMetadataJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jwks/json': typeof JwksJsonRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/oauth/client-metadata/json': typeof OauthClientMetadataJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jwks/json'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/oauth/client-metadata/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jwks/json'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/oauth/client-metadata/json'
  id:
    | '__root__'
    | '/'
    | '/jwks/json'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/oauth/client-metadata/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JwksJsonRoute: typeof JwksJsonRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthLoginApiRoute: typeof OauthLoginApiRoute
  OauthLogoutRoute: typeof OauthLogoutRoute
  OauthClientMetadataJsonRoute: typeof OauthClientMetadataJsonRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/logout': {
      id: '/oauth/logout'
      path: '/oauth/logout'
      fullPath: '/oauth/logout'
      preLoaderRoute: typeof OauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login-api': {
      id: '/oauth/login-api'
      path: '/oauth/login-api'
      fullPath: '/oauth/login-api'
      preLoaderRoute: typeof OauthLoginApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwks/json': {
      id: '/jwks/json'
      path: '/jwks/json'
      fullPath: '/jwks/json'
      preLoaderRoute: typeof JwksJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/client-metadata/json': {
      id: '/oauth/client-metadata/json'
      path: '/oauth/client-metadata/json'
      fullPath: '/oauth/client-metadata/json'
      preLoaderRoute: typeof OauthClientMetadataJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JwksJsonRoute: JwksJsonRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthLoginApiRoute: OauthLoginApiRoute,
  OauthLogoutRoute: OauthLogoutRoute,
  OauthClientMetadataJsonRoute: OauthClientMetadataJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
