/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OauthLogoutRouteImport } from './routes/oauth/logout'
import { Route as OauthLoginApiRouteImport } from './routes/oauth/login-api'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as ApiTapEventsRouteImport } from './routes/api/tap-events'
import { Route as DashboardHooksHookIdRouteImport } from './routes/dashboard/hooks/$hookId'
import { Route as ApiHooksAddRepoRouteImport } from './routes/api/hooks/addRepo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLogoutRoute = OauthLogoutRouteImport.update({
  id: '/oauth/logout',
  path: '/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginApiRoute = OauthLoginApiRouteImport.update({
  id: '/oauth/login-api',
  path: '/oauth/login-api',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/dashboard/new',
  path: '/dashboard/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapEventsRoute = ApiTapEventsRouteImport.update({
  id: '/api/tap-events',
  path: '/api/tap-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHooksHookIdRoute = DashboardHooksHookIdRouteImport.update({
  id: '/dashboard/hooks/$hookId',
  path: '/dashboard/hooks/$hookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksAddRepoRoute = ApiHooksAddRepoRouteImport.update({
  id: '/api/hooks/addRepo',
  path: '/api/hooks/addRepo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/tap-events': typeof ApiTapEventsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/hooks/addRepo': typeof ApiHooksAddRepoRoute
  '/dashboard/hooks/$hookId': typeof DashboardHooksHookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tap-events': typeof ApiTapEventsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/hooks/addRepo': typeof ApiHooksAddRepoRoute
  '/dashboard/hooks/$hookId': typeof DashboardHooksHookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/tap-events': typeof ApiTapEventsRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/login-api': typeof OauthLoginApiRoute
  '/oauth/logout': typeof OauthLogoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/hooks/addRepo': typeof ApiHooksAddRepoRoute
  '/dashboard/hooks/$hookId': typeof DashboardHooksHookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/tap-events'
    | '/dashboard/new'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/dashboard/'
    | '/api/hooks/addRepo'
    | '/dashboard/hooks/$hookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/tap-events'
    | '/dashboard/new'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/dashboard'
    | '/api/hooks/addRepo'
    | '/dashboard/hooks/$hookId'
  id:
    | '__root__'
    | '/'
    | '/api/tap-events'
    | '/dashboard/new'
    | '/oauth/callback'
    | '/oauth/login-api'
    | '/oauth/logout'
    | '/dashboard/'
    | '/api/hooks/addRepo'
    | '/dashboard/hooks/$hookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTapEventsRoute: typeof ApiTapEventsRoute
  DashboardNewRoute: typeof DashboardNewRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthLoginApiRoute: typeof OauthLoginApiRoute
  OauthLogoutRoute: typeof OauthLogoutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiHooksAddRepoRoute: typeof ApiHooksAddRepoRoute
  DashboardHooksHookIdRoute: typeof DashboardHooksHookIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/logout': {
      id: '/oauth/logout'
      path: '/oauth/logout'
      fullPath: '/oauth/logout'
      preLoaderRoute: typeof OauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login-api': {
      id: '/oauth/login-api'
      path: '/oauth/login-api'
      fullPath: '/oauth/login-api'
      preLoaderRoute: typeof OauthLoginApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tap-events': {
      id: '/api/tap-events'
      path: '/api/tap-events'
      fullPath: '/api/tap-events'
      preLoaderRoute: typeof ApiTapEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/hooks/$hookId': {
      id: '/dashboard/hooks/$hookId'
      path: '/dashboard/hooks/$hookId'
      fullPath: '/dashboard/hooks/$hookId'
      preLoaderRoute: typeof DashboardHooksHookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/addRepo': {
      id: '/api/hooks/addRepo'
      path: '/api/hooks/addRepo'
      fullPath: '/api/hooks/addRepo'
      preLoaderRoute: typeof ApiHooksAddRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTapEventsRoute: ApiTapEventsRoute,
  DashboardNewRoute: DashboardNewRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthLoginApiRoute: OauthLoginApiRoute,
  OauthLogoutRoute: OauthLogoutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiHooksAddRepoRoute: ApiHooksAddRepoRoute,
  DashboardHooksHookIdRoute: DashboardHooksHookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
